language: node_js
node_js:
- '6'
before_install:
- ./ci/travis/create_npmrc.js
- npm install istanbul mocha babel-cli -g
install:
- npm install babel-preset-es2015
- npm install
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
- ./ci/travis/publish.js
- ./ci/travis/push_scaffold.js
